baseURL = "/"
title = "作ったものとか"
copyright = "(C) 2017 Shuhei Kubota"

theme = "derty"

hasCJKLanguage = true
enableGitInfo = true
enableEmoji = true

[params]
  [params.derty]
    outdatedUnit = "year"
    outdatedLimit = 1
    outdatedMessageHTML = "最終更新日から %s 以上が経過しています。<br/>内容が古くなっている可能性があるのでご注意ください。"
    
    profileHTML = "<object type='image/svg+xml' alt='follow chimatter at twitter' data='https://img.shields.io/badge/@chimatter-Follow-blue?style=for-the-badge&logo=twitter&logoColor=white&link=https://twitter.com/intent/user?screen_name=chimatter&link=https://twitter.com/intent/follow?screen_name=chimatter'></object>"
    #profileDescription = "いえーい"

    # 空白の場合は 📄 が使われる。 HTML 可。
    #latestIconHTML = "<img src='/abc.png' />"

    pagefind = true
  
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

  [markup.highlight]
    codeFences = true
    noClasses = false
    style = 'pastie'

[services]
  [services.googleAnalytics]
    id = "G-TK21YTEJFM"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
